"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

import sys
from setuptools import setup

main_script = "MediaQueue.py"

if sys.platform == "darwin":
    extra_options = dict(
        app=[main_script],
        options=dict(
            py2app=dict(
                argv_emulation=True,
                iconfile="mediaqueue.icns")),
        setup_requires=["py2app"])

elif sys.platform == "win32":
    extra_options = dict(
        app=[main_script],
        zipfile=None,
        options=dict(
            py2exe=dict(
                bundle_files=1,
                iconfile="mediaqueue.ico")),
        setup_requires=["py2exe"])
else:
    extra_options = dict(scripts=[main_script])

setup(name="MediaQueue", **extra_options)
